  name: Deploy to Hostinger

  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
    deploy:
      name: Deploy WordPress to Hostinger
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install SSH Pass
          run: sudo apt-get update && sudo apt-get install -y sshpass

        - name: Deploy wp-content to Hostinger
          env:
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
            SSH_PATH: ${{ secrets.SSH_PATH }}
          run: |
            echo "🚀 Iniciando deploy para Hostinger..."

            # Deploy do tema
            echo "📦 Fazendo upload do tema Hello Elementor..."
            sshpass -p "$SSH_PASSWORD" scp -P $SSH_PORT -o
  StrictHostKeyChecking=no -r \
              wp-content/themes/hello-elementor \
              $SSH_USER@$SSH_HOST:$SSH_PATH/wp-content/themes/

            # Deploy dos plugins
            echo "📦 Fazendo upload dos plugins..."
            sshpass -p "$SSH_PASSWORD" scp -P $SSH_PORT -o
  StrictHostKeyChecking=no -r \
              wp-content/plugins/* \
              $SSH_USER@$SSH_HOST:$SSH_PATH/wp-content/plugins/

            echo "✅ Deploy concluído com sucesso!"
            echo "🌐 Site: https://feelup.com.br"

        - name: Verify deployment
          env:
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
            SSH_PATH: ${{ secrets.SSH_PATH }}
          run: |
            echo "🔍 Verificando arquivos no servidor..."
            sshpass -p "$SSH_PASSWORD" ssh -p $SSH_PORT -o
  StrictHostKeyChecking=no \
              $SSH_USER@$SSH_HOST \
              "ls -la $SSH_PATH/wp-content/themes/hello-elementor && \
               ls -la $SSH_PATH/wp-content/plugins/ | head -10"
            echo "✅ Verificação completa!"
